# yarn suppress warnings
# https://github.com/vuejs/vitepress/issues/472

packageExtensions:
  '@docsearch/react@*':
    peerDependenciesMeta:
      '@types/react':
        optional: true
      'react':
        optional: true
      'react-dom':
        optional: true
